### ISSUE TITLE
update.sh has wrong line 29?

### ISSUE THREAD

**Issue by washran** [rollingrhinoremix/rhino-update#19] opened 2022-04-16 06:22 UTC
if [ ! -f "$HOME/.rhino/config/snapdpurge"]; then 
Shouldn't space be snapdpurge" ]; ?

**Comment by ajstrongdev** [comment] 2022-04-16 09:58
I apologize but I am unable to understand what the issue is with the script by your description, would it be alright if you went more indepth with the issue?

**Comment by raluvy95** [comment] 2022-04-16 10:07
Fixed in #20

**Comment by ajstrongdev** [comment] 2022-04-16 10:07
Closed

**Closed as completed by ajstrongdev** 2022-04-16 10:07 UTC
